server {
     listen 443 ssl;
     server_name tatahere.42.fr;

	 ssl_protocols TLSv1.2;
	 ssl_certificate		/nginx/certificate.pem;
	 ssl_certificate_key	/nginx/privatekey.pem;
     root /var/www/wordpress;
     index index.php index.html;

     location / {
             try_files $uri $uri/ /index.php?$args;
     }

     location ~ \.php$ {
             include fastcgi_params;
             fastcgi_pass my_wordpress:9000;
             fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
             fastcgi_param PATH_INFO $fastcgi_path_info;
     }
}
