CREATE OR REPLACE DATABASE MARIADB_DB ;

CREATE OR REPLACE USER MARIADB_USER@'%' IDENTIFIED BY 'MARIADB_PASSWORD';
CREATE OR REPLACE USER MARIADB_USER@'localhost' IDENTIFIED BY 'MARIADB_PASSWORD';

GRANT ALL ON MARIADB_DB.* TO MARIADB_USER@'%';
GRANT ALL ON MARIADB_DB.* TO MARIADB_USER@'localhost';

FLUSH PRIVILEGES;

